### PR TITLE
feat(react): place dropdown with Popper

### PR DESCRIPTION
**Pull request by francoischalifour**
## Description

This PR adds support for dropdown placement, based on [Popper.js](https://github.com/popperjs/popper-core).

## API

Although Popper allows to show floating elements on the left, right, top and bottom (each with vertical and horizontal variants), this API only supports the two main use cases for an autocomplete experience: `start` (bottom left) and `end` (bottom right)

```ts
interface AutocompleteProps {
  // ...
  dropdownPlacement: 'start' | 'end';
}
```

```ts
<Autocomplete
  // ...
  // Usage for DocSearch
  dropdownPlacement="end"
  // Usage for InstantSearch (by default)
  dropdownPlacement="start"
/>
```

For now, users can only choose the placement of the dropdown (`start` or `end`). The Popper.js API is not leaked – I believe this is enough. If ever power users want to access the modifiers, we can either create an API or advise them to create their own renderer.

### `start`

image

### `end`

image

## Customize

Users are able to tweak the margin in CSS because this Popper configuration doesn't reset the `margin` style property.

```css
.algolia-autocomplete-dropdown {
  margin-top: 0;
}

@media (min-width: 600px) {
  .algolia-autocomplete-dropdown {
    margin-top: 5px;
  }
}
```

<details>
<summary>See outdated</summary>

*EDIT*: this was fixed in e6cfd05809ee7bd3fc33923fbbb9b7bec2ddfe84.

To add custom responsive styles, user will have to use `!important` in CSS because Popper add `styles` to the dropdown DOM elements (which takes precedence over `class`).

```css
.algolia-autocomplete-dropdown {
  margin-top: -5px !important;
}
```

This removes the hardcoded `offset` in JavaScript.

I came across the [`applyStyles`](https://popper.js.org/docs/v2/modifiers/apply-styles/) option documentation but it's incomplete. I'm not sure if there's a better way to override the computed styles (cc @FezVrasta).

A pattern that must be possible is that the dropdown takes the full width and height on mobile. I'd appreciate your input on how that would be possible with Popper @FezVrasta.

</details>

### CODE REVIEW

**Review by s-pace — APPROVED** [review]
If you can not do that without dependency, this LGTM

**Comment by FezVrasta** [comment]
If you'd like to make the popper wide as its reference element, you could add a custom modifier to alter the popper size:

https://codepen.io/FezVrasta/pen/gOpaoeL

To override the styles applied by Popper you can do the same thing I did in the codepen above in the "sameWidth" modifier.

**Comment by francoischalifour** [comment]
@s-pace For now we're using a subset of Popper's API. If we considerer that it's too much for our use, we can remove the dependency as long as we don't leak its API.

@FezVrasta Thank you for the snippet, this is going to be useful. I don't understand why Popper is opinionated about adding the `margin: 0px` style which breaks the implementation in this case. How would you go about adding styles in CSS classes that don't get overridden by Popper? This is the `style` value that it generates:

```css
{
  position: absolute;
  left: 0px;
  top: 0px;
  margin: 0px; /* this is not needed and is too opinionated for us */
  right: auto;
  bottom: auto;
  transform: /* dynamically computed */;
}
```

**Comment by FezVrasta** [comment]
margins on popper elements are not supported, consumers should define popper offsets with the `offset` modifier. https://popper.js.org/docs/v2/modifiers/offset/

I'm not 100% sure why do we apply `margin` but it may be to prevent issues when users accidentally set the margin.
https://popper.js.org/docs/v2/migration-guide/#4-remove-all-css-margins

**Comment by francoischalifour** [comment]
With DocSearch, we are used to adding a margin on desktop so that the search box and the dropdown don't touch (mainly because the two elements don't have the same width):

image

On mobile however, we'd like to allow such designs (full width, full height, no space between the search box and the dropdown):

image

For this kind of style features, users would expect to be able to achieve this with only CSS. However, with this solution, it wouldn't be the case. Does that make sense?

**Comment by FezVrasta** [comment]
Yes it does, unfortunately margins cause a lot of positioning issues so we had to remove them from the equation.

As an alternative, you could have the popper container be a transparent element, and inside it position the dropdown element, with the needed conditional margins.

**Comment by FezVrasta** [comment]
If you decide to use CSS margins and take the risks, you can add this modifier to unset them and leave the user-defined one:

```
{
  name: 'unsetMargins',
  enabled: true,
  fn: ({ state }) => { state.styles.popper.margin = null; }
  requires: ['computeStyles'],
  phase: 'beforeWrite',
}
```

**Comment by FezVrasta** [comment]
@atomiks suggested to do something like this:

```
const yourLibrary = userProvidedMediaQuery => createPopper(x, y, {
  modifiers: [
    {
      name: 'offset',
      options: {
        offset: () => {
          if (userProvidedMediaQuery.matches) {
            return [0, 0];
          } else {
            return [0, 10];
          }
        }
      }
    } 
  ]
});

yourLibrary(window.matchMedia('(max-width: 500px)'));

```

This should allow Popper to conditionally apply different offsets based on the browser window width.

**Comment by francoischalifour** [comment]
@atomiks' solution doesn't allow users to provide their own CSS theme, which is the main point of this discussion 🙂. The goal here is not to find a one-time solution but rather to empower users to not have to think it terms of JavaScript API for such a feature.

I'll go with https://github.com/francoischalifour/autocomplete.js/pull/25#issuecomment-585879128 for now, thanks!

Just to anticipate what problems can arise, what are the main cases where ignoring `margin` in Popper cause trouble?

**Comment by francoischalifour** [comment]
Note that there seem to have a mistyping in the library because this raises a TypeScript error and `undefined` doesn't unset the CSS property:

```ts
state.styles.popper.margin = null;
```

> Type 'null' is not assignable to type 'string | undefined'.

**Comment by atomiks** [comment]
I think it should be an empty string `""` instead of `null`.

The margins cause issues when the popper flips to a different axis (e.g. bottom to right), if that never happens it should be okay to use margins

**Comment by francoischalifour** [comment]
That sounds good – I'm satisfied with the current solution!

Thank you @FezVrasta and @atomiks, your help and reactivity are very much appreciated!

**Comment by atomiks** [comment]
I do think there is a dev warning if using margins though (2.0.1+)...

**Comment by francoischalifour** [comment]
I don't get a warning with this Popper configuration with version 2.0.6.

**Review by eunjae-lee — APPROVED** [review]
The exposed API seems good!

**Pull request merged**
